name: Mac Build

on: workflow_dispatch

jobs:
  interpreter:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Interpreter
      run: scripts/mac/compile_interpreter.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: interpreter
        path: bin/build/interp/mac/vortex
  modules:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Modules
      run: scripts/mac/compile_modules.sh

    - name: List modules
      id: modules
      run: |
        for module in bin/build/modules/mac/*; do
          if [ -d "$module" ]; then
            echo "Uploading $module as artifact"
            name=$(basename "$module")
            cp -r "$module" "$GITHUB_WORKSPACE/$name"
            echo "::set-output name=artifact::$GITHUB_WORKSPACE/$name"
          fi
        done

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.modules.outputs.artifact }}
        path: ${{ steps.modules.outputs.artifact }}