name: Mac Build

on: workflow_dispatch

jobs:
  interpreter:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Interpreter
      run: scripts/mac/compile_interpreter.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: interpreter
        path: bin/build/interp/mac/vortex
  modules:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download SDL stuff
      run: | 
        brew install sdl2;
        brew install sdl2_image;
        brew install sdl2_ttf;
        brew install sdl2_mixer;

        rm -r Modules/modules/sdl/lib/*

        cp /usr/local/Cellar/sdl2/*/lib/*.dylib Modules/modules/sdl/lib
        cp /usr/local/Cellar/sdl2/*/lib/*.a Modules/modules/sdl/lib

        cp /usr/local/Cellar/sdl2_image/*/lib/*.dylib Modules/modules/sdl/lib
        cp /usr/local/Cellar/sdl2_image/*/lib/*.a Modules/modules/sdl/lib

        cp /usr/local/Cellar/sdl2_ttf/*/lib/*.dylib Modules/modules/sdl/lib
        cp /usr/local/Cellar/sdl2_ttf/*/lib/*.a Modules/modules/sdl/lib

        cp /usr/local/Cellar/sdl2_mixer/*/lib/*.dylib Modules/modules/sdl/lib
        cp /usr/local/Cellar/sdl2_mixer/*/lib/*.a Modules/modules/sdl/lib

    - name: Compile Modules
      run: scripts/mac/compile_modules.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: modules
        path: bin/build/modules/mac/**/*