name: Win Build

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        default: '1.0-win'
        required: true
        type: string

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Interpreter
      run: scripts/win/compile_interpreter.sh
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: interpreter
        path: bin/build/interp/win/vortex.exe

    - name: Compile Modules
      run: scripts/win/compile_modules.sh
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: modules
        path: bin/build/modules/win/**/*

    - name: Create dist folder
      run: |
        mkdir -p dist
        cp bin/build/interp/win/vortex dist
        for module in bin/build/modules/win/*; 
        do
        m=$(basename $module)
        pushd bin/build/modules/win
        powershell Compress-Archive ${m} "${m}.zip";
        popd
        mv bin/build/modules/win/${m}.zip dist
        done
      shell: bash

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ inputs.tag }} dist/* \
            --repo="$GITHUB_REPOSITORY" \
            --title="Vortex-Win-${{ inputs.tag }}" \
            --generate-notes \
            --latest
      shell: bash